---
galaxy_info:
    description: Role for managing systemd services, units and journald
    author: "arillso (@arillso)"
    license: MIT
    min_ansible_version: "2.15"
    platforms:
        - name: Debian
          versions:
              - bullseye
              - bookworm
        - name: Ubuntu
          versions:
              - focal
              - jammy
              - noble
        - name: EL
          versions:
              - "8"
              - "9"

    galaxy_tags:
        - system
        - systemd
        - service
        - unit
        - journald
        - logging

dependencies: []
