---
- name: Configure APT settings
  ansible.builtin.template:
      src: etc/apt/apt.conf.d/config.j2
      dest: "/etc/apt/apt.conf.d/{{ _pkg_config_item.priority | default('90') }}-{{ _pkg_config_item.name }}"
      owner: root
      group: root
      mode: "0644"
      backup: true
  become: true
  loop: "{{ packages_apt_conf }}"
  loop_control:
      loop_var: _pkg_config_item
  notify: "packages update cache"
