---
galaxy_info:
    role_name: facts
    author: "arillso"
    description: "Enterprise-grade system facts collection and MOTD generation for Linux systems"
    company: "arillso"
    license: "MIT"
    min_ansible_version: "2.12"

    platforms:
        - name: Ubuntu
          versions:
              - focal
              - jammy
              - noble
        - name: Debian
          versions:
              - bullseye
              - bookworm
        - name: EL
          versions:
              - "8"
              - "9"

    galaxy_tags:
        - system
        - facts
        - motd
        - monitoring
        - information
        - banner
        - ssh
        - cloud
        - infrastructure

dependencies: []

collections:
    - community.general
