# ============================================================================
# File: roles/shell/handlers/main.yml
# ============================================================================
---
# Shell role handlers

- name: "Restart ssh service"
  ansible.builtin.systemd_service:
      name: "{{ _ssh_service_name }}"
      state: restarted
  vars:
      _ssh_service_name: >-
          {{ _shell_ssh_service_names[ansible_facts['os_family']] |
             default(_shell_ssh_service_names['default']) }}
  when: ansible_facts['service_mgr'] == 'systemd'
  listen: "Restart ssh service"
