---
# Internal variables for bitwarden_secrets role

# Architecture mapping for download URLs
_bitwarden_secrets_arch_map:
    x86_64: "x86_64-unknown-linux-gnu"
    aarch64: "aarch64-unknown-linux-gnu"
    armv7l: "armv7-unknown-linux-gnueabihf"
